# Generated by Django 5.2.10 on 2026-04-23 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cameralocation_detectionlog_lecture_alert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Present', max_length=12)),
                ('reason', models.CharField(blank=True, default='', max_length=240)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lecture')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
            options={
                'unique_together': {('student', 'lecture', 'date')},
            },
        ),
    ]
