# Generated by Django 5.2.12 on 2026-04-24 08:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_lectureattendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_type', models.CharField(choices=[('classroom', 'Classroom'), ('canteen', 'Canteen'), ('corridor', 'Corridor'), ('entrance', 'Entrance/Gate'), ('library', 'Library'), ('lab', 'Lab'), ('other', 'Other')], max_length=20)),
                ('location_desc', models.CharField(blank=True, default='', max_length=200)),
                ('camera_index', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='detectionlog',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='detectionlog',
            name='student',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='detection',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='student',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='lecture',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='lecture',
            old_name='name',
            new_name='subject',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='alert',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='resolved_by',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='to_role',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='to_user',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='hod',
        ),
        migrations.RemoveField(
            model_name='lectureattendance',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='lectureattendance',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='alert',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='notify_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='notify_hod',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='alert',
            name='snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='alert_snapshots/'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='core.lecture'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='marked_by',
            field=models.CharField(default='camera', max_length=20),
        ),
        migrations.AddField(
            model_name='lecture',
            name='branch',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lecture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture',
            name='day',
            field=models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday')], default='exit', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture',
            name='year',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='lectureattendance',
            name='marked_by',
            field=models.CharField(default='camera', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='face_folder',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='face_image_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='face_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('cheating', '⚠️ Attendance Cheating'), ('unknown_face', '👤 Unknown Face Detected'), ('campus_no_att', '🏫 On Campus Without Attendance'), ('late', '⏰ Late Arrival'), ('manual', '📝 Manual Alert')], max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='alert',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='core.student'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], default='present', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.student'),
        ),
        migrations.AlterField(
            model_name='lectureattendance',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_attendance', to='core.lecture'),
        ),
        migrations.AlterField(
            model_name='lectureattendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], default='present', max_length=10),
        ),
        migrations.AlterField(
            model_name='lectureattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_attendance', to='core.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='known_faces/'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'lecture', 'date')},
        ),
        migrations.AddField(
            model_name='alert',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.camera'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.camera'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lectures', to='core.camera'),
        ),
        migrations.AddField(
            model_name='lectureattendance',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.camera'),
        ),
        migrations.CreateModel(
            name='FaceRegistrationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('capturing', 'Capturing'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('photos_taken', models.IntegerField(default=0)),
                ('target_count', models.IntegerField(default=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_sessions', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('faculty', 'Faculty'), ('hod', 'Head of Department')], default='faculty', max_length=10)),
                ('branch', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=15)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='faculty_photos/')),
                ('face_registered', models.BooleanField(default=False)),
                ('face_image_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Faculty',
            },
        ),
        migrations.CreateModel(
            name='CameraLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('unknown', 'Unknown')], max_length=10)),
                ('unknown_name', models.CharField(blank=True, default='Unknown', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='snapshots/')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.camera')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera_logs', to='core.student')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera_logs', to='core.faculty')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='alert',
            name='notify_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_alerts', to='core.faculty'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lectures', to='core.faculty'),
        ),
        migrations.DeleteModel(
            name='CameraLocation',
        ),
        migrations.DeleteModel(
            name='DetectionLog',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
